/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/iphone-17-pro.glb 
*/

import React, { useRef, useState, useEffect, useCallback } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { CameraZoom } from "../canvas/IPhoneCanvas";

type GLTFResult = {
  nodes: {
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane001_2: THREE.Mesh;
    Plane001_3: THREE.Mesh;
    Plane001_4: THREE.Mesh;
    Plane001_5: THREE.Mesh;
  };
  materials: {
    ["iphone17pro-textures"]: THREE.Material;
    ["Frame "]: THREE.Material;
    Glass: THREE.Material;
    Black: THREE.Material;
    ["Inner black"]: THREE.Material;
    Lense: THREE.Material;
  };
};

const MODEL_Y = -2.6;

export function IPhone(props: React.JSX.IntrinsicElements["group"]) {
  // Make sure this GLTF asset string matches your explicit file location path!
  const { nodes, materials } = useGLTF(
    "/models/iphone-17-pro.glb",
  ) as unknown as GLTFResult;

  const groupRef = useRef<THREE.Group>(null);
  const [isOpen, setIsOpen] = useState(false);
  const toggle = useCallback(() => setIsOpen((p) => !p), []);

  useEffect(() => {
    window.addEventListener("click", toggle);
    return () => window.removeEventListener("click", toggle);
  }, [toggle]);

  useFrame(({ clock }) => {
    const t = clock.getElapsedTime();

    if (groupRef.current) {
      // Smoothly lerp back to 0 vertically when open, float gently when closed
      groupRef.current.position.y = isOpen
        ? THREE.MathUtils.lerp(groupRef.current.position.y, 0, 0.05)
        : Math.sin(t * 0.8) * 0.12;

      // Smoothly spin 180 degrees (Math.PI) around the Y axis when clicked
      groupRef.current.rotation.y = THREE.MathUtils.lerp(
        groupRef.current.rotation.y,
        isOpen ? Math.PI : 0,
        0.05,
      );
    }
  });

  return (
    <>
      <CameraZoom isOpen={isOpen} />

      {/* We pass incoming props to the outer group, use our tracking groupRef,
        and apply the static MODEL_Y offset configuration cleanly.
      */}
      <group
        {...props}
        ref={groupRef}
        position={[0, MODEL_Y, 0]}
        dispose={null}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={1.26}>
          <mesh
            geometry={nodes.Plane001.geometry}
            material={materials["iphone17pro-textures"]}
          />
          <mesh
            geometry={nodes.Plane001_1.geometry}
            material={materials["Frame "]}
          />
          <mesh
            geometry={nodes.Plane001_2.geometry}
            material={materials.Glass}
          />
          <mesh
            geometry={nodes.Plane001_3.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Plane001_4.geometry}
            material={materials["Inner black"]}
          />
          <mesh
            geometry={nodes.Plane001_5.geometry}
            material={materials.Lense}
          />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/models/iphone-17-pro.glb");
