/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/iphone.glb 
Author: Ranguel (https://sketchfab.com/Ranguel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-17-pro-4541aa8a28324b33a2baaf81d263aaec
Title: iPhone 17 Pro
*/

import React, { useRef, useState, useEffect, useCallback, JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import {
  CameraZoom,
  CLOSED_DISTANCE,
  OPENED_DISTANCE,
} from "../canvas/IPhoneCanvas";

type GLTFResult = {
  nodes: { [key: string]: THREE.Mesh };
  materials: { [key: string]: THREE.Material };
};

export function IPhone(
  props: JSX.IntrinsicElements["group"] & { onTransitionComplete: () => void },
) {
  const { nodes, materials } = useGLTF("/iphone.glb") as unknown as GLTFResult;

  const groupRef = useRef<THREE.Group>(null);
  const [isOpen, setIsOpen] = useState(false);
  const toggle = useCallback(() => setIsOpen((p) => !p), []);

  useEffect(() => {
    window.addEventListener("click", toggle);
    return () => window.removeEventListener("click", toggle);
  }, [toggle]);
  useFrame((state) => {
    if (groupRef.current) {
      // AUTOMATED ROTATION DIRECTION:
      // It checks if your closed distance is a negative number.
      // If it's negative, it uses the inverted rotation. If positive, it uses standard rotation.
      const isCameraBehind = CLOSED_DISTANCE < 0;

      const targetRotationY = isOpen
        ? isCameraBehind
          ? Math.PI
          : 0
        : isCameraBehind
          ? 0
          : Math.PI;

      groupRef.current.rotation.y = THREE.MathUtils.lerp(
        groupRef.current.rotation.y,
        targetRotationY,
        0.05,
      );
    }

    // Dynamic distance math handles the rest automatically
    const targetZ = isOpen ? OPENED_DISTANCE : CLOSED_DISTANCE;
    state.camera.position.z = THREE.MathUtils.lerp(
      state.camera.position.z,
      targetZ,
      0.05,
    );
    state.camera.lookAt(0, 0, 0);

    if (isOpen && Math.abs(state.camera.position.z - targetZ) < 0.05) {
      props.onTransitionComplete();
    }
  });

  return (
    <>
      <CameraZoom isOpen={isOpen} />

      {/* Main tracker group is locked flat in the center of your canvas [0, 0, 0] */}
      <group
        {...props}
        ref={groupRef}
        position={[0, 0, 0]}
        rotation={[0, Math.PI, 0]}
        dispose={null}
      >
        {/* --- Original 3D Hardware Model Components --- */}
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Aluminum}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Plastic_antena}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Plastic_USB_port}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Camera_filter}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Tint_back_glass}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Metal_Screw}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Frosted_glass}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Tint_back_glass}
        />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Glass} />

        <group
          position={[0.022, 0.061, -0.007]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.352, 0.51, 0.352]}
        >
          <mesh geometry={nodes.Object_20.geometry} material={materials.Lens} />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.Sapphire_miror}
          />
        </group>

        <group
          position={[0.022, 0.061, -0.008]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[1.003, 1, 1.003]}
        >
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.Sapphire_miror}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials.Mirror_filter}
          />
        </group>

        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.Aluminum}
        />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Frame} />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.Camera_filter}
        />

        <group
          position={[0.022, 0.041, -0.008]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[1.003, 1, 1.003]}
        >
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials.Sapphire_miror}
          />
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials.Mirror_filter}
          />
        </group>

        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.Aluminum}
        />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Frame} />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.Camera_filter}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.Lens}
          position={[0.022, 0.041, -0.006]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.92, 1.568, 0.92]}
        />

        <group
          position={[0.004, 0.051, -0.008]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[1.003, 1, 1.003]}
        >
          <mesh
            geometry={nodes.Object_41.geometry}
            material={materials.Sapphire_miror}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials.Mirror_filter}
          />
        </group>

        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.Aluminum}
        />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Frame} />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.Camera_filter}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials.Lens}
          position={[0.004, 0.051, -0.007]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[1.23, 1, 1.23]}
        />

        <mesh geometry={nodes.Object_44.geometry} material={materials.Lens} />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.Camera_filter}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.Plastic_LED}
        />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Frame} />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.Metal_Screw}
        />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Frame} />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.Display}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.Metal_Screw}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.Metal_Screw}
        />
      </group>
    </>
  );
}

useGLTF.preload("/iphone.glb");
