/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mac-draco.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Mac(props) {
  const { nodes, materials } = useGLTF("/mac-draco.glb") as any;

  // 1. Core State and References
  const [isOpen, setIsOpen] = useState(false); // Starts closed (false)
  const lidRef = useRef<THREE.Group>(null);

  // 2. Exact Radian Angle Logic
  // Math.PI * 0.5 represents 90 degrees.
  // In this model structure, adding 1.57 radians folds the screen flat against the base.
  const LID_CLOSED = 1.57;
  const LID_OPEN = 0.014; // The original open/tilted position from your GLTF file

  // 3. Handle Canvas/Window Click Events
  useEffect(() => {
    const toggle = () => setIsOpen((prev) => !prev);
    window.addEventListener("click", toggle);
    return () => window.removeEventListener("click", toggle);
  }, []);

  // 4. Smooth Animation Loop Frame Interpolation
  useFrame(() => {
    if (lidRef.current) {
      const targetRotation = isOpen ? LID_OPEN : LID_CLOSED;

      // Linearly interpolates the rotation angle on every frame
      lidRef.current.rotation.x = THREE.MathUtils.lerp(
        lidRef.current.rotation.x,
        targetRotation,
        0.06, // Lower = slower/smoother opening animation speed
      );
    }
  });

  return (
    <group {...props} dispose={null}>
      {/* 5. Bound the lidRef directly onto the hinge group component */}
      <group
        ref={lidRef}
        position={[0.002, -0.038, 0.414]}
        rotation={[LID_CLOSED, 0, 0]} // Starts resting at the closed angle value
      >
        <group position={[0, 2.965, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["matte.001"]}
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials["screen.001"]}
          />
        </group>
      </group>

      {/* Static Laptop Base Sections */}
      <mesh
        geometry={nodes.keyboard.geometry}
        material={materials.keys}
        position={[1.793, 0, 3.451]}
      />
      <group position={[0, -0.1, 3.394]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.aluminium}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials.trackpad}
        />
      </group>
      <mesh
        geometry={nodes.touchbar.geometry}
        material={materials.touchbar}
        position={[0, -0.027, 1.201]}
      />
    </group>
  );
}

useGLTF.preload("/mac-draco.glb");
