/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mac-draco.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF, Html, PerspectiveCamera } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

// --- CAMERA CONFIGURATION ---
// Lower CAMERA_Y to move down.
// Increase CAMERA_Z to move back if the camera feels too close when you go low.
const CAMERA_Y = 0.5;
const CAMERA_Z = 18;

export function Mac(props) {
  const { nodes, materials } = useGLTF("/mac-draco.glb") as any;

  const [isOpen, setIsOpen] = useState(false);
  const lidRef = useRef<THREE.Group>(null);

  const LID_CLOSED = 1.57;
  const LID_OPEN = 0.014;

  // 2. Handle Canvas/Window Click Events
  useEffect(() => {
    const toggle = () => setIsOpen((prev) => !prev);
    window.addEventListener("click", toggle);
    return () => window.removeEventListener("click", toggle);
  }, []);

  // 3. Smooth Animation Loop Frame Interpolation
  useFrame(() => {
    if (lidRef.current) {
      const targetRotation = isOpen ? LID_OPEN : LID_CLOSED;

      lidRef.current.rotation.x = THREE.MathUtils.lerp(
        lidRef.current.rotation.x,
        targetRotation,
        0.06,
      );
    }
  });

  return (
    <group {...props} dispose={null}>
      {/* STATIC SCENE CAMERA 
          Tied directly to the configuration variables at the top of the file.
      */}
      <PerspectiveCamera
        makeDefault
        position={[0, CAMERA_Y, CAMERA_Z]}
        fov={45}
      />

      {/* 4. Animated Lid Hinge Group Component */}
      <group
        ref={lidRef}
        position={[0.002, -0.038, 0.414]}
        rotation={[LID_CLOSED, 0, 0]}
      >
        {/* The original 3D laptop lid hardware meshes */}
        <group position={[0, 2.965, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["matte.001"]}
          />
        </group>

        <group position={[0, 2.965, -0.05]} rotation={[0, 0, 0]}>
          <Html
            transform
            pointerEvents={isOpen ? "auto" : "none"}
            distanceFactor={2.2}
            style={{
              width: "100%",
              height: "100%",
            }}
          >
            <div
              className="laptop-html-screen"
              onMouseDown={(e) => e.stopPropagation()}
              onMouseUp={(e) => e.stopPropagation()}
              onClick={(e) => e.stopPropagation()}
              onPointerDown={(e) => e.stopPropagation()}
              onPointerUp={(e) => e.stopPropagation()}
              style={{
                background: "#121212",
                color: "#ffffff",
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                userSelect: "none",
              }}
            >
              <h1 style={{ fontSize: "8rem", color: "#007aff" }}>
                HI My Friend
              </h1>
            </div>
          </Html>
        </group>
      </group>

      {/* Static Laptop Base Sections */}
      <mesh
        geometry={nodes.keyboard.geometry}
        material={materials.keys}
        position={[1.793, 0, 3.451]}
      />
      <group position={[0, -0.1, 3.394]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.aluminium}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials.trackpad}
        />
      </group>
      <mesh
        geometry={nodes.touchbar.geometry}
        material={materials.touchbar}
        position={[0, -0.027, 1.201]}
      />
    </group>
  );
}

useGLTF.preload("/mac-draco.glb");
