/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mac-draco.glb 
*/

import React, { useRef, useState, JSX, useEffect } from "react";
import { useGLTF, Html, PerspectiveCamera } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

// Module-level mouse — updated from window so the intro overlay doesn't block it
const mouse = { x: 0, y: 0 };
import { CLOSED_DISTANCE, OPENED_DISTANCE } from "../canvas/LaptopCanvas"; // Adjust path as needed

// --- CAMERA CONFIGURATION ---
const CAMERA_Y = 0.5;
const CAMERA_LOOK_Y = 3;

type GLTFResult = {
  nodes: {
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    keyboard: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    touchbar: THREE.Mesh;
  };
  materials: {
    aluminium: THREE.Material;
    ["matte.001"]: THREE.Material;
    keys: THREE.Material;
    trackpad: THREE.Material;
    touchbar: THREE.Material;
  };
};

// Explicit type intersection via the '&' operator
type MacBookProps = JSX.IntrinsicElements["group"] & {
  isOpen: boolean;
  onTransitionComplete: () => void;
};

export function MacBook({
  isOpen,
  onTransitionComplete,
  ...props
}: MacBookProps) {
  const { nodes, materials } = useGLTF(
    "/mac-draco.glb",
  ) as unknown as GLTFResult;

  const [showHtml, setShowHtml] = useState(false);

  const outerGroupRef = useRef<THREE.Group>(null);
  const lidRef = useRef<THREE.Group>(null);
  const isAnimating = useRef(false);
  const prevIsOpen = useRef(isOpen);

  // Track mouse from window so the intro overlay doesn't block it
  useEffect(() => {
    const onMove = (e: MouseEvent) => {
      mouse.x =  (e.clientX / window.innerWidth)  * 2 - 1;
      mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
    };
    window.addEventListener("mousemove", onMove);
    return () => window.removeEventListener("mousemove", onMove);
  }, []);

  const LID_CLOSED = 1.57;
  const LID_OPEN = 0.1;

  useFrame((state) => {
    // 1. Safe state detection replacing the original useEffect rule break
    if (isOpen !== prevIsOpen.current) {
      isAnimating.current = true;
      if (isOpen) setShowHtml(true);
      prevIsOpen.current = isOpen;
    }

    // 2. Maintain the vertical lookAt focus anchor point
    state.camera.lookAt(0, CAMERA_LOOK_Y, 0);

    // 3. Dynamically interpolate the camera's Z position
    const targetCameraZ = isOpen ? OPENED_DISTANCE : CLOSED_DISTANCE;
    state.camera.position.z = THREE.MathUtils.lerp(
      state.camera.position.z,
      targetCameraZ,
      0.08,
    );

    if (outerGroupRef.current) {
      // cursor influence — only while closed (pre-click state)
      const cursorY = !isOpen ? Math.PI + mouse.x * 0.45 : 0;
      const cursorX = !isOpen ? mouse.y * -0.35 : 0;
      const cursorZ = !isOpen ? mouse.x * mouse.y * -0.12 : 0;

      // 4. Smooth Y-Axis Rotation Flip + cursor tilt
      outerGroupRef.current.rotation.y = THREE.MathUtils.lerp(
        outerGroupRef.current.rotation.y,
        cursorY,
        0.08,
      );

      // cursor X tilt (pitch)
      outerGroupRef.current.rotation.x = THREE.MathUtils.lerp(
        outerGroupRef.current.rotation.x,
        cursorX,
        0.08,
      );

      // subtle Z roll for diagonal movement
      outerGroupRef.current.rotation.z = THREE.MathUtils.lerp(
        outerGroupRef.current.rotation.z,
        cursorZ,
        0.08,
      );

      // 5. SUBTLE IDLE FLOATING: Sits at -0.05 when closed, snaps cleanly to 0 when open
      const t = state.clock.getElapsedTime();
      const targetY = isOpen ? 0 : -0.05 + Math.sin(t * 1.0) * 0.02;
      outerGroupRef.current.position.y = THREE.MathUtils.lerp(
        outerGroupRef.current.position.y,
        targetY,
        0.05,
      );
    }

    // 6. Handle the lid hinge rotation opening and closing
    if (lidRef.current) {
      const targetRotation = isOpen ? LID_OPEN : LID_CLOSED;
      lidRef.current.rotation.x = THREE.MathUtils.lerp(
        lidRef.current.rotation.x,
        targetRotation,
        0.06,
      );

      if (isAnimating.current) {
        const distanceToTarget = Math.abs(
          lidRef.current.rotation.x - targetRotation,
        );
        if (distanceToTarget < 0.002) {
          isAnimating.current = false;
          if (!isOpen) {
            setShowHtml(false); // Unmounts HTML context securely on complete fold close
          }
        }
      }
    }

    // 7. Handshake execution trigger to flip into DOM layout visibility on zoom close match
    if (isOpen && Math.abs(state.camera.position.z - targetCameraZ) < 0.8) {
      onTransitionComplete();
    }
  });

  return (
    <group ref={outerGroupRef}>
      <group {...props} dispose={null}>
        <PerspectiveCamera
          makeDefault
          position={[0, CAMERA_Y, CLOSED_DISTANCE]}
          fov={45}
        />

        {/* Animated Lid Hinge Group Component */}
        <group
          ref={lidRef}
          position={[0.002, -0.038, 0.414]}
          rotation={[LID_CLOSED, 0, 0]}
        >
          {/* The original 3D laptop lid hardware meshes */}
          <group position={[0, 2.965, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cube008.geometry}
              material={materials.aluminium}
            />
            <mesh
              geometry={nodes.Cube008_1.geometry}
              material={materials["matte.001"]}
            />
          </group>

          <group position={[0, 3.05, -0.05]} rotation={[0, 0, 0]}>
            <Html
              transform
              pointerEvents={isOpen ? "auto" : "none"}
              distanceFactor={2.2}
              style={{
                width: "100%",
                height: "100%",
                display: showHtml ? "block" : "none",
              }}
            >
              <div
                className="laptop-html-screen"
                onMouseDown={(e) => e.stopPropagation()}
                onMouseUp={(e) => e.stopPropagation()}
                onClick={(e) => e.stopPropagation()}
                onPointerDown={(e) => e.stopPropagation()}
                onPointerUp={(e) => e.stopPropagation()}
                style={{
                  background: "#121212",
                  color: "#ffffff",
                  width: "1516px",
                  height: "992px",
                  display: "flex",
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                  userSelect: "none",
                  borderRadius: "30px",
                  opacity: isOpen ? 1 : 0,
                  transition: "opacity 0.15s ease-out",
                }}
              ></div>
            </Html>
          </group>
        </group>

        {/* Static Laptop Base Sections */}
        <mesh
          geometry={nodes.keyboard.geometry}
          material={materials.keys}
          position={[1.793, 0, 3.451]}
        />
        <group position={[0, -0.1, 3.394]}>
          <mesh
            geometry={nodes.Cube002.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.Cube002_1.geometry}
            material={materials.trackpad}
          />
        </group>
        <mesh
          geometry={nodes.touchbar.geometry}
          material={materials.touchbar}
          position={[0, -0.027, 1.201]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mac-draco.glb");
