/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mac-draco.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF, Html, PerspectiveCamera } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

// --- CAMERA CONFIGURATION ---
const CAMERA_Y = 0.5;

// --- DYNAMIC ZOOM TARGETS ---
const ZOOMED_OUT_Z = 18; // Camera depth when laptop is closed
const ZOOMED_IN_Z = 15; // Camera depth when laptop is open (lower = closer)

// --- VERTICAL POSITION CONFIGURATION ---
const CAMERA_LOOK_Y = 3;

export function MacBook(props) {
  const { nodes, materials } = useGLTF("/mac-draco.glb") as any;

  const [isOpen, setIsOpen] = useState(false);
  const [showHtml, setShowHtml] = useState(false);

  const lidRef = useRef<THREE.Group>(null);
  const isAnimating = useRef(false);

  const LID_CLOSED = 1.57;
  const LID_OPEN = 0.1;

  // 2. Handle Canvas/Window Click Events
  useEffect(() => {
    const toggle = () => {
      isAnimating.current = true;

      setIsOpen((prev) => {
        if (!prev) setShowHtml(true);
        return !prev;
      });
    };
    window.addEventListener("click", toggle);
    return () => window.removeEventListener("click", toggle);
  }, []);

  // 3. Smooth Animation Loop, Camera Focus, and Dynamic Zoom
  useFrame((state) => {
    // 1. Maintain the vertical lookAt focus anchor point
    state.camera.lookAt(0, CAMERA_LOOK_Y, 0);

    // 2. Dynamically interpolate the camera's Z position based on isOpen state
    const targetCameraZ = isOpen ? ZOOMED_IN_Z : ZOOMED_OUT_Z;
    state.camera.position.z = THREE.MathUtils.lerp(
      state.camera.position.z,
      targetCameraZ,
      0.05, // Adjust this value to make the camera zoom faster or slower
    );

    // 3. Handle the lid hinge rotation
    if (lidRef.current) {
      const targetRotation = isOpen ? LID_OPEN : LID_CLOSED;

      lidRef.current.rotation.x = THREE.MathUtils.lerp(
        lidRef.current.rotation.x,
        targetRotation,
        0.06,
      );

      if (isAnimating.current) {
        const distanceToTarget = Math.abs(
          lidRef.current.rotation.x - targetRotation,
        );

        if (distanceToTarget < 0.002) {
          isAnimating.current = false;

          if (!isOpen) {
            setShowHtml(false);
          }
        }
      }
    }
  });

  return (
    <group {...props} dispose={null}>
      {/* Starting position setup uses our initial default closed depth */}
      <PerspectiveCamera
        makeDefault
        position={[0, CAMERA_Y, ZOOMED_OUT_Z]}
        fov={45}
      />

      {/* 4. Animated Lid Hinge Group Component */}
      <group
        ref={lidRef}
        position={[0.002, -0.038, 0.414]}
        rotation={[LID_CLOSED, 0, 0]}
      >
        {/* The original 3D laptop lid hardware meshes */}
        <group position={[0, 2.965, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["matte.001"]}
          />
        </group>

        <group position={[0, 3.05, -0.05]} rotation={[0, 0, 0]}>
          <Html
            transform
            pointerEvents={isOpen ? "auto" : "none"}
            distanceFactor={2.2}
            style={{
              width: "100%",
              height: "100%",
              display: showHtml ? "block" : "none",
            }}
          >
            <div
              className="laptop-html-screen"
              onMouseDown={(e) => e.stopPropagation()}
              onMouseUp={(e) => e.stopPropagation()}
              onClick={(e) => e.stopPropagation()}
              onPointerDown={(e) => e.stopPropagation()}
              onPointerUp={(e) => e.stopPropagation()}
              style={{
                background: "#121212",
                color: "#ffffff",
                width: "1516px",
                height: "992px",
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                userSelect: "none",
                borderRadius: "30px",
                opacity: isOpen ? 1 : 0,
                transition: "opacity 0.15s ease-out",
              }}
            >
              <h1 style={{ fontSize: "8rem", color: "#007aff" }}>
                HI My Friend
              </h1>
            </div>
          </Html>
        </group>
      </group>

      {/* Static Laptop Base Sections */}
      <mesh
        geometry={nodes.keyboard.geometry}
        material={materials.keys}
        position={[1.793, 0, 3.451]}
      />
      <group position={[0, -0.1, 3.394]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.aluminium}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials.trackpad}
        />
      </group>
      <mesh
        geometry={nodes.touchbar.geometry}
        material={materials.touchbar}
        position={[0, -0.027, 1.201]}
      />
    </group>
  );
}

useGLTF.preload("/mac-draco.glb");
